### ISSUE TITLE
AES/GCM encryption with 32 key length doesn't work on MacOS

### ISSUE THREAD

**Issue by tiurikov** [infrastructor/infrastructor#102]
I have noticed that encryption does not work on MacOS using 32 key length, but works fine on Linux. Considering to reduce key length to 16 as a solution. Investigation is needed.

**Comment by tuwid** [comment]
Fixed on PR https://github.com/infrastructor/infrastructor/pull/103

**Comment by tiurikov** [comment]
Fixed, closed.
