### ISSUE TITLE
request for comment:  weighted DNS record

### ISSUE THREAD

**Issue by tuwid** [infrastructor/infrastructor#108]
I noticed in the documentation that in the managed inventory the route53 section:

> In the example above a single EC2 instance will be created first. After that Infrastructor will search for instances match {'front-server:true'} criteria and create an A-type DNS record using their public IP addresses. In case no instance have been found using the criteria specified, but there is a pre-existing DNS record - the record will be deleted.

In case of multiple instances will this create a weighted DNS record ?

**Comment by tiurikov** [comment]
closing the issue due to inactivity
