### ISSUE TITLE
wiki typos

### ISSUE THREAD

**Issue by bernhardhuber** [infrastructor/infrastructor#145]
hi, 

As I was reading the wiki pages of this excellent project, I stumbled upon some typos in the wiki.

# Action-Reference

https://github.com/infrastructor/infrastructor/wiki/Action-Reference

I think _fetch_ is the correct spelling 
* fetche -> fetch:

> fetche a file from a remote host

I think _available_ is the correct spelling

* avalable, avaiable -> available:
* avalable in
* avaiable for 

I think _block_ is the correct spelling:

* blok -> block

> a regular expression to search a text blok to replace

# Inventory-Reference

https://github.com/infrastructor/infrastructor/wiki/Inventory-Reference

I think _private_ is the correct spelling:

* privete -> private:

> SSH privete key file passphrase

**Comment by tiurikov** [comment]
Hi @bernhardhuber!

Many thanks for highlighting this! Will try to find some time on the weekend to fix it.

**Comment by bernhardhuber** [comment]
Hi @tiurikov 

I cloned the wiki locally, and fixed some typos.
I have attache a patch of the typos. I hope it helps you fixing the typos.
[infrastructor_wiki_patch1.txt](https://github.com/infrastructor/infrastructor/files/7765200/infrastructor_wiki_patch1.txt)

I don't know to create a git pull request from a local patch, so sorry for that inconvenience.

**Comment by tiurikov** [comment]
Everything should be fixed know. Thank you!
