### ISSUE TITLE
wiki definition failsafe versus code failfast

### ISSUE THREAD

**Issue by bernhardhuber** [infrastructor/infrastructor#147]
Hi, @tiurikov 

I 'd like to inform you of another typo or code typo:

Action-Reference.md says at Shell/Attributes
```
| failsafe  | Boolean | yes      | true          | stop execution if exit code is not 0 |
```

but grooy code uses `failfast` in Node.groovy, and ShellAction.groovy.

As I 'm not sure which wording you prefer, I have opened this issue.

**Comment by tiurikov** [comment]
Hey @bernhardhuber! fixed, thanks!
