### ISSUE TITLE
delete after creation feature request

### ISSUE THREAD

**Issue by tuwid** [infrastructor/infrastructor#49]
Can we have a flag on the image builder feature for something like `deleteAfterCreation` = `true` so we can have the temporary machine deleted after we make an image out of it ?

**Comment by tiurikov** [comment]
Hey, 

I think the **terminateInstance** property is the thing you are looking for:

```groovy
awsImageBuilder {
    awsAccessKeyId = ""
    awsAccessSecretKey = ""
    awsRegion = ""
    imageName = "my-custom-ubuntu"
    usePublicIp = ""
    terminateInstance = true
    node {
        imageId = ""
        instanceType = ""
        securityGroupIds = []
        ...
    } 
}.build { ... }
```

**Comment by tuwid** [comment]
thanks, it works
