### ISSUE TITLE
Kotlin DSL

### ISSUE THREAD

**Issue by codematix** [infrastructor/infrastructor#90]
Are there plans to implement a Kotlin DSL as well? Given that it has support for writing expressive DSLs and its gaining momentum.

**Comment by tiurikov** [comment]
Having support for many languages looks like a promising idea to me. It definitely would be a step ahead for Infrastructor. But I'm not an expert in Kotlin to say it can be implemented or not. It requires some preliminary investigation. I have no plans to work on it so far. But I would be happy to approve a pull request!

**Comment by codematix** [comment]
Thanks for sharing your views on this @tiurikov, I would like to contribute the Kotlin version. I am forking your repository to see what I can do to bring the DSL in.

**Comment by tiurikov** [comment]
@codematix it would be an amazing feature! Thank you!
Let me know if you have any questions about the code structure so we can think tougher how to make it better and friendlier for the Kotlin DSL implementation.

**Comment by tiurikov** [comment]
closing the issue due to inactivity
