### ISSUE TITLE
ssh Passphrase

### ISSUE THREAD

**Issue by phormanns** [infrastructor/infrastructor#96]
My ssh key is passphrase protected.
Is there a way to provide a ssh passphrase?

**Comment by tiurikov** [comment]
@phormanns unfortunately there is no way to do it do far. Only SSH private keys without passphrase are supported. But it should not be hard to implement and definitely make sense to have. I will plan this feature for the next release!

**Comment by phormanns** [comment]
thank you for replying, 
an additional param should do the job:
http://www.docjar.org/docs/api/com/jcraft/jsch/JSch.html#addIdentity(String,byte)

**Comment by tiurikov** [comment]
Yep, I'm also thinking about this solution. I will try it out!
