### ISSUE TITLE
sudo Password

### ISSUE THREAD

**Issue by phormanns** [infrastructor/infrastructor#97]
On the remote server I'd like to switch from my personal login to a service user. 
That is possible by sudo. But it needs an sudo password. Is there a way to provide that password?

**Comment by tiurikov** [comment]
@phormanns Unfortunately there is no special way to specify a _sudo_ password for a user. 
In such case I would consider to introduce a user which can connect by SSH and have enough permissions to configure whatever it supposed to configure. As an alternative you can try run a shell action this way: 
```groovy
inlineInventory {
  // inventory definition here
}.provision {
  def SECRET = input message: 'please, enter a password: ', secret: true
  task name: 'example', actions: {
      // user devops can run sudo but has to provide a password to do so.
      def result = shell user: "devops", command: """
          echo '$SECRET' | sudo -S cat /etc/sudoers
      """
      info "result: $result.output"
  }
}
```

please let me know if you have an idea of a better implementation, I will think about how to make it real.

**Comment by phormanns** [comment]
I'd prefer a special sudo-action in addition to the shell-action

**Comment by phormanns** [comment]
But a special sudo-action would not help in case of file upload. Any better idea?

**Comment by tiurikov** [comment]
I'm thinking about this approach:

```groovy 
inlineInventory {
  // inventory definition here
}.provision {
  def SECRET = input message: 'please, enter a password: ', secret: true

  task name: 'example', actions: {
      shell user: "devops", sudopass: SECRET, command: """
          cat /etc/sudoers
      """
      upload (user: 'devops', sudopass: SECRET) {
          source = ''
          target = ''
      }
      template (user: 'devops', sudopass: SECRET) {
          source = ''
          target = ''
          bindings = [:]
      }
  }
}
```

So, here the underlying "sudo -s -u" command will be executed with the specified password, e.g. `echo 'secret' | sudo -S -s -u user command` All actions (currently 10) need to be updated. I will try to experiment with the syntax to see if it covers all possible cases.

**Comment by tiurikov** [comment]
fixed, closed.
